import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#0056b3",
        "secondary-fixed": "#dde3eb",
        "error-container": "#93000a",
        "primary-fixed": "#d7e2ff",
        "on-primary-fixed-variant": "#004491",
        "on-primary-container": "#bbd0ff",
        "on-tertiary": "#263143",
        "inverse-surface": "#e4e1e9",
        "secondary-fixed-dim": "#c1c7cf",
        "on-secondary-fixed": "#161c22",
        "on-error-container": "#ffdad6",
        "surface-bright": "#39383e",
        "tertiary-fixed": "#d8e3fb",
        "surface-container-highest": "#35343a",
        "on-surface": "#e4e1e9",
        "surface-dim": "#131318",
        "surface-tint": "#acc7ff",
        "on-secondary-container": "#afb6bd",
        "on-primary-fixed": "#001a40",
        "tertiary-container": "#4e596d",
        "secondary-container": "#41474e",
        secondary: "#c1c7cf",
        "outline-variant": "#424752",
        error: "#ffb4ab",
        outline: "#8c909e",
        "on-background": "#e4e1e9",
        "on-error": "#690005",
        "on-tertiary-fixed": "#111c2d",
        "on-secondary": "#2b3137",
        "surface-container": "#1f1f25",
        "on-tertiary-container": "#c5d0e8",
        "primary-fixed-dim": "#acc7ff",
        "surface-container-low": "#1b1b20",
        primary: "#acc7ff",
        "surface-container-lowest": "#0e0e13",
        background: "#131318",
        surface: "#131318",
        tertiary: "#bcc7de",
        "tertiary-fixed-dim": "#bcc7de",
        "surface-container-high": "#2a292f",
        "surface-variant": "#35343a",
        "inverse-primary": "#115cb9",
        "on-surface-variant": "#c2c6d4",
        "on-secondary-fixed-variant": "#41474e",
        "on-tertiary-fixed-variant": "#3c475a",
        "on-primary": "#002f67",
        "inverse-on-surface": "#303036",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        unit: "8px",
        "section-gap": "48px",
        "stack-lg": "32px",
      },
      fontFamily: {
        "label-lg": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Newsreader", "serif"],
        "headline-md": ["Chivo", "sans-serif"],
        "headline-xl": ["Chivo", "sans-serif"],
        "headline-xl-mobile": ["Chivo", "sans-serif"],
        "headline-lg": ["Chivo", "sans-serif"],
        "body-md": ["Newsreader", "serif"],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};
export default config;
